apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cqapcnx0m-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cqapcnx0m-java-quarkus-gitops